### ISSUE TITLE
No external dependencies

### ISSUE THREAD

**Issue by jpralves** [altLab/altBot#12]
The code should run withou external dependencies of files like index.html and/or js files.
A basic version should be included statically into the code. # #

**Comment by pangelo** [comment]
Sure, since we are only serving a single page and it's not bound to change much, I guess we can just embed everything into a static raw string inside the sketch. This will also make it easier for beginners to upload the sketch without needing additional tools to upload the data.

Later, if we make more complex javascript apps (like porting the mirobot onboard IDE) we'll need to separate out the js files.

**Comment by jpralves** [comment]
The code should be in a resource file like basicControl.h so that changes to it (or removing it) may not change the main code.

**Comment by pangelo** [comment]
Right, it makes sense to keep them separate from the rest of the code, and opens up the possibility to make a script that generates the header file from the actual web source files (e.g it could minify them to save memory).

**Comment by guardajoao** [comment]
This could seem offtopic...
But i AM so happy to see people working together...
...Yes we can....

Em 14/02/2017 20:53, "Pedro Ângelo" <notifications@github.com> escreveu:
